MODEL:
  BACKBONE:
    TYPE: 'ResNet'
    ResNet:
      DEPTH: 18
      WEIGHTS: "IMAGENET1K_V1"
DATASETS:
  TRAIN: "SPAUR_768x512"
  TRAIN_SPLIT: "train"
  VAL: "SPAUR_768x512"
  VAL_SPLIT: "val"
INPUT:
  SIZE: [512, 768]
  CROP_TYPE: "random"
  RANDOM_ERASE:
    ENABLED: True
  RANDOM_SHORTER_SIDE:
    ENABLED: True
    MIN_SIZE: (360, 640)
    MAX_SIZE: 960
  COLOR_JITTER:
    ENABLED: True
    BRIGHTNESS: (0.7, 1.3)
    CONTRAST: (0.75, 1.25)
    SATURATION: (0.75, 1.25)
    HUE: (-0.17, 0.17)
  NORMALIZE: True
OPTIMIZER:
  LR: 0.001
  SCHEDULER:
    TYPE: "ExpLR"
    STEP_INTERVAL: 250
    EXPLR:
      GAMMA: 0.98
TRAINER:
  NUM_WORKERS: 4
  EVAL_INTERVAL: 2500
  LOG_INTERVAL: 20
  CHECKPOINT_INTERVAL: 2500
  ITERATIONS: 60000
  MS_EVAL: True
LOSS:
  TYPE: "bce"
  TOP_K_PERCENT_PIXELS: 0.10
EVALUATORS: ("euclidean_distance_evaluator", "visualization_evaluator")
OUTPUT_DIR: "output/r18_res_768x512_bce_zavada_best_hpm10_randomcrop"
